<!DOCTYPE html>
<html lang="en">
<head>
<title>$page.title$ · $page.properties.("project.name")$</title>
<meta name="description" content="$page.properties.("project.description")$"/>
<link rel="stylesheet" type="text/css" href="css/custom-print.css"/>
</head>
<body>
$page.properties.("project.name")$
$page.properties.("project.version")$

<p>This is the cover page. Above should be the project name, paradox-test, and its version, 0.1-SNAPSHOT.</p>

</body>
</html>