<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
<title>$page.properties.("project.name")$</title>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<meta name="description" content='$page.properties.("project.description")$'/>
<link href="https://fonts.googleapis.com/css?family=Roboto:100normal,100italic,300normal,300italic,400normal,400italic,500normal,500italic,700normal,700italic,900normal,900italicc" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="$page.base$lib/foundation/dist/foundation.min.css"/>
<link rel="stylesheet" type="text/css" href="$page.base$css/page.css"/>
<link rel="stylesheet" type="text/css" href="$page.base$css/single.css"/>
<link rel="stylesheet" type="text/css" href="$page.base$css/print.css"/>

</head>

<body>

<div class="print-cover-title">$page.properties.("project.name")$</div>
<div class="print-cover-version">Version $page.properties.("project.version")$</div>

</html>
